drinks/urls.py
from django.urls import path 
from drinks.views import *
app_name = 'drinks'
urlpatterns = [
   path('eno/',eno,name='eno'),
   path('lassi/',lassi,name='lassi'), 
]

food/urls.py
from django.urls import path
from food.views import *
app_name='food'
urlpatterns=[
    path('chickenbiriyani/',chickenbiriyani,name='chickenbiriyani'),
    path('rasgola/',rasgola,name='rasgola'),
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import food,drinks

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('drinks/',include('drinks.urls')),
]

drinks/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

drinks/views.py
from django.shortcuts import render

# Create your views here.
def eno(request):
    return render(request,'eno.html')

def lassi(request):
    return render(request,'lassi.html')

food/views.py
from django.shortcuts import render

# Create your views here.
def chickenbiriyani(request):
    return render(request,'chickenbiriyani.html')

def rasgola(request):
    return render (request,'rasgola.html')

templates/chickenbiriyani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hydrabadi chicken biriyani famous in all over India</h1>
        <a href="{% url 'drinks:eno' %}"><h1>ENO</h1></a>
        <a href="{% url 'drinks:lassi' %}"><h1>LASSI</h1></a>
        <a href="{% url 'food:rasgola' %}"><h1>RASGOLA</h1></a>
    </center>
    
</body>
</html>

templates/eno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>ENO is good for acidity</h1>
        <a href="{% url 'drinks:lassi' %}">LASSI</a>
        <a href="{% url 'food:chickenbiriyani' %}"><h1>CHICKENBIRIYANI</h1></a>
        <a href="{% url 'food:rasgola' %}"><h1>RASGOLA</h1></a>
    </center>
</body>
</html>

templates/lassi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Lassi is a good drinks in summer season</h1>
        <a href="{% url 'drinks:eno' %}"><h1>ENO</h1></a>
        <a href="{% url 'food:chickenbiriyani' %}"><h1>CHICKENBIRIYANI</h1></a>
        <a href="{% url 'food:rasgola' %}"><h1>RASGOLA</h1></a>
    </center>
</body>
</html>

templates/rasgola.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Rasgola is famous in Odisha</h1>
        <a href="{% url 'drinks:eno' %}"><h1>ENO</h1></a>
        <a href="{% url 'food:chickenbiriyani' %}"><h1>CHICKENBIRIYANI</h1></a>
        <a href="{% url 'drinks:lassi' %}"><h1>LASSI</h1></a>
    </center>
</body>
</html>